WIFI_DEVICE = "wlan0"
DEFAULT_HOTSPOT_NAME = "RaspHotspot"
DEFAULT_HOTSPOT_PASSWORD = "password"
SERVICE_NAME = "hotspot.service"
APP_DIRECTORY = "config_wifi_page"
ETC_APP_DIRECTORY = "/etc/config_wifi_page"
REQUIREMENTS_FILE = "../requirements.txt"
